{% set version = "4.11.1" %}

# sometimes part of the tag name (with the hyphen separator).
# however, this has changed without warning (with a different sha256) in the past...
# {% set patch_level = "-1" %}

package:
  name: antlr
  # this version drives maven options in build.sh/bld.bat
  # version: {{ version }}{{ patch_level.replace("-", "_") }}
  version: {{ version }}

source:
  url: https://github.com/antlr/antlr{{ version[0] }}/archive/{{ version }}.tar.gz
  sha256: 81f87f03bb83b48da62e4fc8bfdaf447efb9fb3b7f19eb5cbc37f64e171218cf

build:
  number: 1

requirements:
  build:
    - maven
  run:
    - openjdk

test:
  commands:
    - antlr4
    - grun

about:
  home: https://www.antlr.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: ANother Tool for Language Recognition (ANTLR).
  description: |
    ANTLR (ANother Tool for Language Recognition) is a powerful parser generator 
    for reading, processing, executing, or translating structured text or binary 
    files.
  dev_url: https://github.com/antlr/antlr4
  doc_url: https://github.com/antlr/antlr4/blob/master/doc/index.md

extra:
  recipe-maintainers:
    - xylar
    - tobias-fischer
    - ocefpaf
    - kwilcox
    - bollwyvl
    - zklaus
