{% set version = "2.7.7" %}

package:
  name: antlr
  version: {{ version }}

source:
  url: http://www.antlr2.org/download/antlr-{{ version }}.tar.gz
  sha256: 853aeb021aef7586bda29e74a6b03006bcb565a755c86b66032d8ec31b67dbb9
  patches:
    - CharScanner.patch

build:
  number: 8
  skip: True  # [win and py<36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - antlr-config --version  # [not win]

about:
  home: http://www.antlr2.org/
  license: BSD-3-clause and GPL-3.0 and Public Domain
  license_file: LICENSE.txt
  summary: 'ANother Tool for Language Recognition (ANTLR)'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
