travis:
  secure:
    BINSTAR_TOKEN: n5f5Ho9Z2ogK8LEWRMa/PDGu19L5/v5ATNfSmFWN5TUlNPQiSGo4K7Mj2vXkMHORn5pN3zOYdnw5BLPzPfjGprU6n3Uz+DtrUgx4bjn0JPR9/41XAV0uOz6U1J/qra/Rbi/HI5CHL0o0imN/4UkkI/VGvawBjQtB9AjcRDhSyH53nFpU1YbKbYy2qnf43wDIMFU4I9JHshkFP/X2ShpRKPEs9T+zVoaZQ4dyruIwE8jEWxrmWUY+yqj4eWPOtELWCTVlY/UpJE6VNWCa8S+NkFhEUloUceZgzo5TuwE6Y4pYBFRqxCCvySBO7npBVovpundc2jMy3RumBnUt5NYEt1xtUkgCCKO/b7QoaoXX3NVL4wuVC3VkSUOa95UUZNfJfaUrIGAN6kzsTZfpTh2FESmKf5iFN5Np1pDRVmmeLY/ixqyw73tFhEG7IzhEWmuIE8mA/52nYOkAcdqd6agjb+b22vnc/hgIhW0CyZ02Dv3DtorDbuvsJgW2iX0fn1ArBLt5jzzDimNyIG2L//m2r3h/+fgsr9bDRo0CH+tUY3MN3nVuiwW1in62n0gFfejso6Isk0jgpvrJ04PutKUSzilDMGfqm3ltKidJbvM0UJZek+rK3gbzBxgTucc7WR9MqGIqLkFxA/SWc5EhV7CTXDJJsbfLoWp5LLDwJEgKDB4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
